Add rest
ilya-sayenko/java-money-splitter pull request #3
Opened 2023-07-14 10:47 UTC by ilya-sayenko

2023-07-25 16:17 UTC, GordPavel requested changes
Совсем нет тестов на rest модуль

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/dao/postgresql/entity/attributeconverter/SplitTypeConverter.java
> +                return 1;
почему бы просто строками не хранить?

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/exception/IncorrectDataException.java
> +public class IncorrectDataException extends RuntimeException {
создай свое базовое исключение и настрой глобальный Handler, чтобы все ошибки запить одинаково

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/PartyServiceImpl.java
> +        if (partyDao.existsSpendingsByParticipantId(participantId)) {
тебе это БД должна выдать. Делаешь удаление, если есть связанные FK, то будет ошибка

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/PartyServiceImpl.java
> +        InputData inputData = prepareInputData(partyId);
вынеси подсчет в отдельный метод

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/PartyServiceImpl.java
> +        if (spending.getSplitType().equals(PartySpending.SplitType.AMOUNT)) {
а зачем тебе при типе AMOUNT запрашивать общую сумму? Просто спроси в списке суммы и все, не нужно дублировать требуемые данные, чтобы приходилось следить за их корректностью

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/proportion/ProportionCalculatorFactory.java
> +public class ProportionCalculatorFactory {
лайк

2023-07-25 16:17 UTC, GordPavel commented on money-splitter-rest/src/main/resources/db/schema.sql
> +(
было бы неплохо, если бы потом добавил liquibase

2023-08-14 16:33 UTC, ilya-sayenko commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/controller/PartyController.java
> +    @DeleteMapping(value = "/{partyId}/participants/{participantId}")
Т.к. participants и spendings относятся именно к party, то я бы этого не делал.

2023-08-14 16:34 UTC, ilya-sayenko commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/dao/postgresql/entity/PartyEntity.java
> +    private BigDecimal totalAmount;
Не хочется при каждом запросе party подзапросом считать totalAmount.

2023-08-21 22:37 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/PartyServiceImpl.java
> +        partyDao.increasePartyAmount(partyId, spending.getAmount());
тут не исправил

2023-08-21 22:38 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/service/impl/PartyServiceImpl.java
> +        if (partyDao.existsSpendingsByParticipantId(participantId)) {
не увидел тут перехвата ошибки нарушения целостности данных

2023-08-21 22:41 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/dao/postgresql/entity/PartyEntity.java
> +    private BigDecimal totalAmount;
давай в лс подискутируем.  я соглашусь, что такое имеет место быть, но давай обсудим

2023-08-21 22:47 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/controller/PartyController.java
> +            @RequestBody UpdateTransactionStatusRequestDto request
я не Имею ввиду обязательно именно json patch пользоваться. прост проблема в том, что есть конвенция, как выглядит тело PATCH методов

в целом я Соглашусь, что это вообще редко используется и редко кем прям соблюдается. поэтому сойдемся на таком варианте)

2023-08-21 22:47 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/dao/postgresql/PartyPostgresDao.java
> +        spendingRepository.save(spendingEntity);
я все ещё не понимаю, почему бы не убрать `@Transient` над `proportions` и тогда сможешь сохранить одним запросом

2023-09-12 16:41 UTC, ilya-sayenko commented on money-splitter-rest/src/main/java/org/example/moneysplitter/rest/dao/postgresql/PartyPostgresDao.java
> +        spendingRepository.save(spendingEntity);
На сколько я понимаю, тогда нужно будет использовать связь @OneToMany, что не очень производительно.

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/cache/model/Cache.java
> +    private String data;
почему бы не сделать его generic? И в маппер засунуть ObjectMapper, который будет конвертировать

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/party/service/impl/PartyServiceImpl.java
> +            throw new GlobalAppException("Internal server error", HttpStatus.INTERNAL_SERVER_ERROR, -1007);
лучше все-таки не делать везде GlobalException, а взять за привычку растить дерево ошибок, на каждую ошибку новое исключение. И все они корнем идут к `GlobalAppException`

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/party/service/impl/PartyServiceImpl.java
> +        Party savedParty = partyDao.saveParty(party);
транзакции не хватает

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/party/service/impl/PartyServiceImpl.java
> +                            .data(objectMapper.writeValueAsString(party))
к сожалению у тебя CacheDAO вытаскивает свой адаптер наружу. Сделаешь generic и тогда достат

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/java/org/example/moneysplitter/party/service/impl/PartyServiceImpl.java
> +        Party party = partyDao.findPartyById(partyId).orElseThrow(PartyNotFoundException::new);
в идеале я бы даже засунул CacheDao внутрь PartyDao

2023-09-18 16:49 UTC, GordPavel commented on money-splitter-rest/src/main/resources/db/postgres/liquibase/changelog.xml
>      <include file="db/postgres/liquibase/tables/tables.xml"/>
а зачем? Как раз наоборот научиться бы наращивать изменения, нельзя удалять из БД уже совершенные миграции

2023-10-02 13:43 UTC, GordPavel approved these changes
LGTM

2023-10-02 20:57 UTC, merged